"""
DaisySMS service codes mapping.

Full list of 500+ services obtained from DaisySMS API getPrices endpoint.
Last updated: 2025-12-08
"""

# Mapping of service codes to human-readable names
SERVICE_CODE_TO_NAME = {
    # ========================================
    # Premium Services ($1.00+)
    # ========================================
    "it": "Cash App",
    "wa": "WhatsApp",
    "chime": "Chime",
    "fb": "Facebook",
    "experian": "Experian",
    "netbenefits": "Fidelity NetBenefits",
    "flip": "Flip",
    "getholdings": "GetHoldings",
    "go": "Google",
    "klarna": "Klarna",
    "kraken": "Kraken",
    "nfcu": "Navy Federal Credit Union",
    "netspend": "Netspend",
    "ozk": "Bank OZK",
    "plaid": "Plaid",
    "unlisted": "Service Not Listed",
    "uprova": "Uprova",
    "yendo": "Yendo",
    "frostbank": "Frost Bank",

    # ========================================
    # Finance & Banking ($0.80)
    # ========================================
    "af247": "AF247",
    "affirm": "Affirm",
    "ally": "Ally Bank",
    "amex": "American Express",
    "aspiration": "Aspiration",
    "axos": "Axos Bank",
    "boa": "Bank of America",
    "bankmobile": "BankMobile",
    "bmoalto": "BMO Alto",
    "bmoharris": "BMO Harris",
    "cashloansexpress": "Cash Loans Express",
    "citi": "Citibank",
    "citizens": "Citizens Bank",
    "current": "Current",
    "dave": "Dave",
    "discover": "Discover",
    "eastwestbank": "East West Bank",
    "everbank": "EverBank",
    "fidelity": "Fidelity",
    "fifththirdbank": "Fifth Third Bank",
    "firstnationalbank": "First National Bank",
    "gbank": "G Bank",
    "golden1": "Golden 1 Credit Union",
    "huntington": "Huntington Bank",
    "keybank": "KeyBank",
    "laa": "LA Account",
    "lightstream": "LightStream",
    "merrilledge": "Merrill Edge",
    "netpayadvance": "NetPayAdvance",
    "navy": "Navy Federal",
    "northone": "NorthOne",
    "onemain": "OneMain Financial",
    "penfed": "PenFed",
    "pnc": "PNC Bank",
    "regions": "Regions Bank",
    "sezzle": "Sezzle",
    "snapfinance": "Snap Finance",
    "sofi": "SoFi",
    "stripe": "Stripe",
    "sunbit": "Sunbit",
    "tdcom": "TD Bank",
    "transunion": "TransUnion",
    "truist": "Truist",
    "usbank": "US Bank",
    "ufb": "UFB Direct",
    "usaa": "USAA",
    "usalliance": "US Alliance",
    "varo": "Varo Bank",
    "wfargo": "Wells Fargo",
    "bo": "Bank Other",
    "schwab": "Charles Schwab",
    "lj": "Lending Club",
    "ts": "PayPal",

    # ========================================
    # Betting & Casino ($0.40-$0.70)
    # ========================================
    "caesars": "Caesars",
    "betfanatics": "Bet Fanatics",
    "ie": "BetMGM",
    "draftkings": "DraftKings",
    "espnbet": "ESPN Bet",
    "fanduel": "FanDuel",
    "hardrockbet": "Hard Rock Bet",
    "chumbacasino": "Chumba Casino",
    "betr": "Betr",
    "kalshi": "Kalshi",

    # ========================================
    # Social Networks
    # ========================================
    "tw": "Twitter/X.com",
    "ig": "Instagram",
    "tg": "Telegram",
    "ds": "Discord",
    "reddit": "Reddit",
    "bluesky": "Bluesky",
    "threads": "Threads",
    "rednote": "RedNote",
    "rumble": "Rumble",
    "vk": "VK",
    "soulapp": "Soul App",
    "nextdoor": "Nextdoor",
    "naver": "Naver",

    # ========================================
    # Dating Apps
    # ========================================
    "happn": "Happn",
    "rt": "Hinge",
    "ashleymadison": "Ashley Madison",
    "dilmil": "Dil Mil",
    "hud": "HUD",
    "ourtime": "OurTime",
    "raya": "Raya",
    "skout": "Skout",
    "stir": "Stir",
    "taimi": "Taimi",
    "blk": "BLK",
    "hitch": "Hitch",
    "doublelist": "DoubleList",

    # ========================================
    # Shopping & E-commerce
    # ========================================
    "am": "Amazon",
    "bestbuy": "Best Buy",
    "footlocker": "Foot Locker",
    "lego": "LEGO",
    "lowes": "Lowe's",
    "samsclub": "Sam's Club",
    "wayfair": "Wayfair",
    "shop": "Shop Pay",
    "albertsons": "Albertsons",
    "dollargeneral": "Dollar General",
    "cvs": "CVS",
    "circlek": "Circle K",
    "vitacost": "Vitacost",
    "vinted": "Vinted",

    # ========================================
    # Email & Communication
    # ========================================
    "mm": "Microsoft/Outlook",
    "pm": "ProtonMail",
    "wx": "WeChat",
    "googlechat": "Google Chat",
    "dialpad": "Dialpad",
    "openphone": "OpenPhone",
    "ring4": "Ring4",
    "pinger": "Pinger",
    "pingme": "PingMe",
    "burner": "Burner",
    "dingtone": "Dingtone",
    "phoner": "Phoner",
    "textr": "Textr",
    "textla": "Textla",
    "sonetel": "Sonetel",
    "sideline": "Sideline",
    "vumber": "Vumber",

    # ========================================
    # Tech & Cloud
    # ========================================
    "anthropologie": "Anthropic/Claude",
    "vercel": "Vercel",
    "hostinger": "Hostinger",
    "godaddy": "GoDaddy",
    "docusign": "DocuSign",
    "twilio": "Twilio",
    "weebly": "Weebly",
    "screenconnect": "ScreenConnect",
    "lightningai": "Lightning AI",

    # ========================================
    # Crypto & Trading
    # ========================================
    "binanceus": "Binance US",
    "cryptocom": "Crypto.com",
    "gemini": "Gemini",
    "robinhood": "Robinhood",
    "etoro": "eToro",
    "public": "Public",
    "wb": "Webull",
    "strike": "Strike",
    "uphold": "Uphold",
    "river": "River",
    "etrade": "E*TRADE",
    "tradingcom": "Trading.com",
    "gcx": "GCX",

    # ========================================
    # Gig Economy & Work
    # ========================================
    "ub": "Uber",
    "instacart": "Instacart",
    "indeed": "Indeed",
    "upwork": "UpWork",
    "shiftkey": "ShiftKey",
    "prolific": "Prolific",
    "oneforma": "OneForma",
    "outlier": "Outlier",

    # ========================================
    # Games & Entertainment
    # ========================================
    "roblox": "Roblox",
    "riot": "Riot Games",
    "cod": "Call of Duty",
    "nexon": "Nexon",
    "gala": "Gala Games",
    "gameflip": "Gameflip",
    "codashop": "Codashop",
    "pixels": "Pixels",
    "epicpull": "Epic Pull",
    "tcgplayer": "TCGPlayer",
    "kktix": "KKTIX",

    # ========================================
    # Food & Delivery
    # ========================================
    "dunkin": "Dunkin'",
    "dutchbros": "Dutch Bros",
    "chickfila": "Chick-fil-A",
    "chipotle": "Chipotle",
    "wingstop": "Wingstop",
    "butcherbox": "ButcherBox",
    "marylous": "Mary Lou's",

    # ========================================
    # Travel & Transportation
    # ========================================
    "airbnb": "Airbnb",
    "hopper": "Hopper",
    "unitedairlines": "United Airlines",
    "waymo": "Waymo",
    "qantas": "Qantas",
    "wheely": "Wheely",
    "rovemiles": "Rove Miles",

    # ========================================
    # Finance Apps & Rewards
    # ========================================
    "acorns": "Acorns",
    "acima": "Acima",
    "afterpay": "Afterpay",
    "albert": "Albert",
    "biltrewards": "Bilt Rewards",
    "bluevine": "Bluevine",
    "cleo": "Cleo",
    "fetchrewards": "Fetch Rewards",
    "foundcom": "Found",
    "go2bank": "GO2bank",
    "greendot": "Green Dot",
    "greenlight": "Greenlight",
    "ibotta": "Ibotta",
    "intuit": "Intuit",
    "kikoff": "Kikoff",
    "klover": "Klover",
    "novo": "Novo",
    "payoneer": "Payoneer",
    "perpay": "Perpay",
    "revolut": "Revolut",
    "stash": "Stash",
    "step": "Step",
    "vm": "Venmo",
    "wallethub": "WalletHub",
    "wealthfront": "Wealthfront",
    "wu": "Western Union",
    "zipco": "Zip",
    "walmartmoneycard": "Walmart MoneyCard",
    "chase": "Chase",
    "karma": "Credit Karma",
    "bridgemoney": "Bridge Money",
    "bossmoney": "Boss Money",
    "bossrevolution": "Boss Revolution",
    "storecash": "StoreCash",
    "slingmoney": "Sling Money",
    "snaplii": "Snaplii",
    "splitdrop": "SplitDrop",
    "spruce": "Spruce",
    "oneapp": "One App",
    "openbank": "OpenBank",
    "relayfi": "Relay Fi",
    "unbank": "Unbank",
    "koho": "KOHO",
    "kudos": "Kudos",
    "klutchcard": "Klutch Card",
    "imprint": "Imprint",
    "inkind": "inKind",
    "grifin": "Grifin",
    "finnfox": "FinnFox",
    "futuregreen": "Future Green",
    "frisbee": "Frisbee",
    "dovetail": "Dovetail",
    "baselane": "Baselane",
    "archer": "Archer",
    "astrafi": "AstraFi",

    # ========================================
    # Surveys & Rewards
    # ========================================
    "brandedsurveys": "Branded Surveys",
    "fivesurveys": "Five Surveys",
    "nicesurveys": "Nice Surveys",
    "topsurveys": "Top Surveys",
    "primeopinion": "Prime Opinion",
    "swag": "Swagbucks",

    # ========================================
    # Misc Services
    # ========================================
    "2redbeans": "2RedBeans",
    "7eleven": "7-Eleven",
    "aarp": "AARP",
    "advanceamerica": "Advance America",
    "classpass": "ClassPass",
    "fedex": "FedEx",
    "gofundme": "GoFundMe",
    "opentable": "OpenTable",
    "resy": "Resy",
    "seatgeek": "SeatGeek",
    "ticketswap": "TicketSwap",
    "turbotenant": "TurboTenant",
    "whatnot": "Whatnot",
    "zillow": "Zillow",
    "zoho": "Zoho",
    "netflix": "Netflix",
    "centurylink": "CenturyLink",
    "chargepoint": "ChargePoint",
    "evgo": "EVgo",
    "healthsafe": "HealthSafe",
    "noonlight": "Noonlight",
    "pelago": "Pelago",
    "patientfi": "PatientFi",
    "innago": "Innago",
    "onlinecheckwriter": "Online Check Writer",
    "riamoneytransfer": "Ria Money Transfer",
    "rebtel": "Rebtel",
    "pureminutes": "Pure Minutes",
    "tradify": "Tradify",
    "rocketreach": "RocketReach",
    "roomies": "Roomies",

    # ========================================
    # Additional Services (alphabetical)
    # ========================================
    "aaa": "AAA",
    "abb": "ABB",
    "abf": "ABF",
    "abk": "ABK",
    "ac": "AC",
    "acz": "ACZ",
    "ada": "ADA",
    "aegpresents": "AEG Presents",
    "aez": "AEZ",
    "afk": "AFK",
    "aft": "AFT",
    "agk": "AGK",
    "airbaton": "Air Baton",
    "ajj": "AJJ",
    "ajn": "AJN",
    "alf": "ALF",
    "alibabacloud": "Alibaba Cloud",
    "alipay": "Alipay",
    "alq": "ALQ",
    "anl": "ANL",
    "apr": "APR",
    "aqt": "AQT",
    "are": "ARE",
    "asf": "ASF",
    "auw": "AUW",
    "axs": "AXS",
    "bbg": "BBG",
    "bcbs": "BCBS",
    "bdx": "BDX",
    "beehiiv": "Beehiiv",
    "bgj": "BGJ",
    "blastbucks": "Blast Bucks",
    "bright": "Bright",
    "bw": "BW",
    "bz": "BZ",
    "cmb": "CMB",
    "cn": "CN",
    "courtyard": "Courtyard",
    "cpulse": "CPulse",
    "currently": "Currently",
    "dg": "DG",
    "dh": "DH",
    "dingcom": "Ding.com",
    "dingdingding": "DingDingDing",
    "dr": "DR",
    "dripshop": "Drip Shop",
    "ep": "EP",
    "ew": "EW",
    "fanaticslive": "Fanatics Live",
    "feastables": "Feastables",
    "feels": "Feels",
    "fet": "FET",
    "fooji": "Fooji",
    "fp": "FP",
    "fu": "FU",
    "gaint": "Gaint",
    "gf": "GF",
    "gp": "GP",
    "hb": "HB",
    "heycash": "HeyCash",
    "hking": "HKing",
    "hotstreak": "Hot Streak",
    "ir": "IR",
    "jointrue": "JoinTrue",
    "juno": "Juno",
    "keitaro": "Keitaro",
    "kt": "KT",
    "layup": "Layup",
    "lf": "LF",
    "luvs": "Luvs",
    "lysted": "Lysted",
    "manus": "Manus",
    "mb": "MB",
    "me": "ME",
    "mj": "MJ",
    "mo": "Mo",
    "mt": "MT",
    "mygiftcardredemption": "MyGiftCardRedemption",
    "nyc": "NYC",
    "oi": "OI",
    "oz": "OZ",
    "pf": "PF",
    "pinata": "Pinata",
    "playful": "Playful",
    "pogo": "Pogo",
    "pvc": "PVC",
    "qo": "QO",
    "qv": "QV",
    "r4r": "R4R",
    "raisin": "Raisin",
    "re": "RE",
    "revel": "Revel",
    "revtrax": "RevTrax",
    "rr": "RR",
    "shippingeasy": "ShippingEasy",
    "shopback": "ShopBack",
    "snakzy": "Snakzy",
    "snipp": "Snipp",
    "super": "Super",
    "swittch": "Swittch",
    "sx": "SX",
    "taobao": "Taobao",
    "tencent": "Tencent",
    "timewall": "TimeWall",
    "tn": "TN",
    "trapcall": "TrapCall",
    "tu": "TU",
    "uf": "UF",
    "upaynet": "UPayNet",
    "upward": "Upward",
    "veo": "Veo",
    "verasight": "Verasight",
    "veriswap": "Veriswap",
    "vi": "VI",
    "vision_engage": "Vision Engage",
    "vz": "VZ",
    "wc": "WC",
    "wert": "Wert",
    "wetalk": "WeTalk",
    "wonder": "Wonder",
    "wr": "WR",
    "ws": "WS",
    "ex": "EX",
    "yay": "Yay",
    "yy": "YY",
    "za": "ZA",
    "zestearn": "Zest Earn",
    "zk": "ZK",
    "zm": "ZM",
    "zyrtec": "Zyrtec",
}

# Full list of all service codes from API
ALL_SERVICE_CODES = [
    "2redbeans", "auw", "7eleven", "aaa", "aarp", "acima", "acorns",
    "advanceamerica", "aegpresents", "af247", "affirm", "afterpay",
    "airbaton", "airbnb", "albert", "albertsons", "alibabacloud",
    "alipay", "ally", "am", "amex", "anthropologie", "pm", "wx",
    "archer", "ashleymadison", "aspiration", "astrafi", "anl", "axos",
    "axs", "qv", "boa", "bankmobile", "baselane", "bcbs", "beehiiv",
    "bdx", "bestbuy", "betfanatics", "ie", "betr", "biltrewards",
    "binanceus", "blastbucks", "bz", "blk", "bluesky", "bluevine",
    "bmoalto", "bmoharris", "bossmoney", "bossrevolution", "brandedsurveys",
    "bridgemoney", "bright", "mo", "burner", "butcherbox", "caesars",
    "apr", "it", "cashloansexpress", "centurylink", "chargepoint",
    "chase", "afk", "chickfila", "chime", "chipotle", "ir",
    "chumbacasino", "circlek", "citi", "citizens", "classpass", "acz",
    "cleo", "abb", "cod", "codashop", "cmb", "re", "cpulse",
    "courtyard", "wc", "karma", "sx", "cryptocom", "current",
    "currently", "cvs", "dave", "zk", "dialpad", "dilmil", "dingcom",
    "dingdingding", "dingtone", "ds", "discover", "docusign",
    "dollargeneral", "ac", "doublelist", "dovetail", "draftkings",
    "dripshop", "dunkin", "dutchbros", "etrade", "eastwestbank", "dh",
    "uf", "epicpull", "espnbet", "etoro", "alq", "everbank", "evgo",
    "experian", "fb", "fanaticslive", "fanduel", "feastables", "fedex",
    "ws", "feels", "fetchrewards", "fet", "fidelity", "netbenefits",
    "fifththirdbank", "finnfox", "firstnationalbank", "fivesurveys",
    "cn", "flip", "fooji", "footlocker", "foundcom", "frisbee",
    "frostbank", "futuregreen", "gaint", "gala", "gameflip", "gbank",
    "gcx", "gemini", "getholdings", "abk", "go2bank", "godaddy",
    "gofundme", "golden1", "go", "googlechat", "gf", "ajn", "greendot",
    "greenlight", "grifin", "yw", "happn", "hardrockbet", "healthsafe",
    "heycash", "rt", "vz", "hitch", "hking", "hopper", "hostinger",
    "hotstreak", "hud", "huntington", "ibotta", "imprint", "indeed",
    "inkind", "innago", "instacart", "ig", "intuit", "agk", "za",
    "jointrue", "juno", "kt", "kalshi", "keitaro", "keybank", "kikoff",
    "kktix", "klarna", "klover", "klutchcard", "koho", "kraken",
    "kudos", "laa", "layup", "riot", "lego", "lightningai",
    "lightstream", "me", "tn", "ex", "lowes", "luvs", "tu", "lysted",
    "manus", "marylous", "abf", "dg", "merrilledge", "mm", "qo", "bgj",
    "mygiftcardredemption", "naver", "navy", "aft", "netpayadvance",
    "netflix", "netspend", "nexon", "nextdoor", "nfcu", "nicesurveys",
    "ew", "noonlight", "northone", "novo", "nyc", "zm", "vm", "oneapp",
    "oneforma", "onemain", "onlinecheckwriter", "dr", "openbank",
    "openphone", "opentable", "ourtime", "outlier", "ozk", "patientfi",
    "payoneer", "ts", "pelago", "penfed", "perpay", "phoner", "fp",
    "pinata", "pinger", "pingme", "pixels", "plaid", "playful", "pf",
    "pnc", "pogo", "oz", "primeopinion", "prolific", "public",
    "pureminutes", "pvc", "qantas", "raisin", "r4r", "raya", "ajj",
    "rebtel", "reddit", "rednote", "regions", "relayfi", "resy",
    "revel", "revolut", "revtrax", "riamoneytransfer", "ring4", "river",
    "robinhood", "roblox", "rocketreach", "roomies", "rovemiles",
    "rumble", "samsclub", "lj", "schwab", "screenconnect", "are",
    "seatgeek", "unlisted", "sezzle", "aez", "shiftkey", "shippingeasy",
    "shop", "shopback", "sideline", "bw", "skout", "aqt", "slingmoney",
    "snakzy", "snapfinance", "fu", "snaplii", "snipp", "sofi",
    "sonetel", "soulapp", "splitdrop", "spruce", "bbg", "stash", "mt",
    "step", "stir", "storecash", "strike", "stripe", "sunbit", "super",
    "swag", "swittch", "taimi", "taobao", "tcgplayer", "tdcom", "tg",
    "ep", "tencent", "asf", "textla", "textr", "threads", "gp",
    "ticketswap", "lf", "timewall", "oi", "topsurveys", "tradify",
    "tradingcom", "transunion", "trapcall", "truist", "ada",
    "turbotenant", "twilio", "hb", "tw", "usbank", "ub", "ufb",
    "unbank", "unitedairlines", "upaynet", "uphold", "uprova", "upward",
    "upwork", "usaa", "usalliance", "varo", "yy", "veo", "verasight",
    "vercel", "veriswap", "vi", "vinted", "vision_engage", "vitacost",
    "vk", "vumber", "wallethub", "wr", "walmartmoneycard", "wayfair",
    "waymo", "wealthfront", "alf", "wb", "weebly", "wfargo", "wert",
    "wu", "wetalk", "whatnot", "wa", "wheely", "wingstop", "bo", "rr",
    "wonder", "mb", "yay", "yendo", "mj", "zestearn", "zillow", "zipco",
    "zoho", "zyrtec"
]


def get_service_name(code: str) -> str:
    """
    Get human-readable name for a service code.

    Args:
        code: Service code

    Returns:
        Service name or formatted code if not found
    """
    return SERVICE_CODE_TO_NAME.get(code, code.replace("_", " ").title())


def get_all_services() -> list:
    """
    Get list of all services with codes and names.

    Returns:
        List of dicts with 'code' and 'name' keys
    """
    return [
        {"code": code, "name": get_service_name(code)}
        for code in ALL_SERVICE_CODES
    ]
