"""add_search_mode_to_telegram_chats

Revision ID: 42cdcc46da40
Revises: a71c76e96e27
Create Date: 2025-11-10 21:36:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cdcc46da40'
down_revision = 'a71c76e96e27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chats', sa.Column('search_mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_chats', 'search_mode')
    # ### end Alembic commands ###
