"""add_telegram_chats_table

Revision ID: a71c76e96e27
Revises: c7cda8d54464
Create Date: 2025-11-10 19:22:43.201425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71c76e96e27'
down_revision = 'c7cda8d54464'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_code', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_index('idx_telegram_chats_access_code', 'telegram_chats', ['access_code'], unique=False)
    op.create_index('idx_telegram_chats_is_active', 'telegram_chats', ['is_active'], unique=False)
    op.create_index('idx_telegram_chats_user_active', 'telegram_chats', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_telegram_chats_user_id', 'telegram_chats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telegram_chats_user_id', table_name='telegram_chats')
    op.drop_index('idx_telegram_chats_user_active', table_name='telegram_chats')
    op.drop_index('idx_telegram_chats_is_active', table_name='telegram_chats')
    op.drop_index('idx_telegram_chats_access_code', table_name='telegram_chats')
    op.drop_table('telegram_chats')
    # ### end Alembic commands ###
