"""Add instant_ssn_searches table

Revision ID: c7cda8d54464
Revises: 245e9ad29e6f
Create Date: 2025-11-10 10:01:07.463289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cda8d54464'
down_revision = '245e9ad29e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instant_ssn_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('search_params', sa.JSON(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ssn_found', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('api_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_charged', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    sa.CheckConstraint('api_cost >= 0', name='check_api_cost_non_negative'),
    sa.CheckConstraint('user_charged >= 0', name='check_user_charged_non_negative'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_instant_ssn_searches_created_at', 'instant_ssn_searches', ['created_at'], unique=False)
    op.create_index('idx_instant_ssn_searches_success', 'instant_ssn_searches', ['success'], unique=False)
    op.create_index('idx_instant_ssn_searches_user_id', 'instant_ssn_searches', ['user_id'], unique=False)
    op.create_index('idx_instant_ssn_searches_user_success', 'instant_ssn_searches', ['user_id', 'success'], unique=False)

    op.alter_column('users', 'worker_role',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    # idx_users_worker_role already created in worker_role_001 migration
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # idx_users_worker_role dropped in worker_role_001 downgrade
    op.drop_index('idx_users_created_at', table_name='users')
    op.alter_column('users', 'worker_role',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.drop_index('idx_instant_ssn_searches_user_success', table_name='instant_ssn_searches')
    op.drop_index('idx_instant_ssn_searches_user_id', table_name='instant_ssn_searches')
    op.drop_index('idx_instant_ssn_searches_success', table_name='instant_ssn_searches')
    op.drop_index('idx_instant_ssn_searches_created_at', table_name='instant_ssn_searches')
    op.drop_table('instant_ssn_searches')
    # ### end Alembic commands ###
