INSERT INTO ssn_database.ssn_mutants (id, firstname, lastname, middlename, address, city, state, zip, phone, email, ssn, dob, source_table, tag)
SELECT
    id,
    firstname,
    lastname,
    if(middlename = '' OR middlename IS NULL,
       anyIf(middlename, middlename != '' AND middlename IS NOT NULL) OVER (PARTITION BY ssn),
       middlename) as middlename,
    if(address = '' OR address IS NULL,
       anyIf(address, address != '' AND address IS NOT NULL) OVER (PARTITION BY ssn),
       address) as address,
    if(city = '' OR city IS NULL,
       anyIf(city, city != '' AND city IS NOT NULL) OVER (PARTITION BY ssn),
       city) as city,
    if(state = '' OR state IS NULL,
       anyIf(state, state != '' AND state IS NOT NULL) OVER (PARTITION BY ssn),
       state) as state,
    if(zip = '' OR zip IS NULL,
       anyIf(zip, zip != '' AND zip IS NOT NULL) OVER (PARTITION BY ssn),
       zip) as zip,
    if(phone = '' OR phone IS NULL,
       anyIf(phone, phone != '' AND phone IS NOT NULL) OVER (PARTITION BY ssn),
       phone) as phone,
    if(email = '' OR email IS NULL,
       anyIf(email, email != '' AND email IS NOT NULL) OVER (PARTITION BY ssn),
       email) as email,
    ssn,
    if(dob = '' OR dob IS NULL,
       anyIf(dob, dob != '' AND dob IS NOT NULL) OVER (PARTITION BY ssn),
       dob) as dob,
    source_table,
    'mutant' as tag
FROM ssn_database.ssn_data
WHERE ssn IN (SELECT ssn FROM ssn_database.duplicate_ssns)
