#!/bin/bash
#
# update-cloudflare-ips.sh
# Script to automatically update Cloudflare IP ranges for nginx real_ip module
#
# Usage:
#   ./update-cloudflare-ips.sh                    # Run manually
#   0 3 * * * /root/soft/scripts/update-cloudflare-ips.sh  # Cron (daily at 3:00 AM)
#
# This script:
#   1. Downloads current Cloudflare IP ranges (IPv4 and IPv6)
#   2. Generates cloudflare-ips.conf with set_real_ip_from directives
#   3. Tests nginx configuration
#   4. Reloads nginx if configuration is valid
#   5. Rolls back to backup if configuration fails
#

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PROJECT_DIR/cloudflare-ips.conf"
BACKUP_FILE="$PROJECT_DIR/cloudflare-ips.conf.backup"
LOG_FILE="/var/log/cloudflare-ips-update.log"
CLOUDFLARE_IPV4_URL="https://www.cloudflare.com/ips-v4"
CLOUDFLARE_IPV6_URL="https://www.cloudflare.com/ips-v6"

# Logging function
log() {
    local level="$1"
    shift
    local message="$*"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] [$level] $message" | tee -a "$LOG_FILE" 2>/dev/null || echo "[$timestamp] [$level] $message"
}

# Error handler
error_exit() {
    log "ERROR" "$1"
    exit 1
}

# Rollback to backup
rollback() {
    if [[ -f "$BACKUP_FILE" ]]; then
        log "INFO" "Rolling back to backup configuration..."
        cp "$BACKUP_FILE" "$CONFIG_FILE"
        log "INFO" "Rollback completed"
    else
        log "WARN" "No backup file found, cannot rollback"
    fi
}

# Download IP ranges from Cloudflare
download_ip_ranges() {
    local url="$1"
    local result

    if command -v curl &> /dev/null; then
        result=$(curl -sf --connect-timeout 10 --max-time 30 "$url") || return 1
    elif command -v wget &> /dev/null; then
        result=$(wget -qO- --timeout=30 "$url") || return 1
    else
        error_exit "Neither curl nor wget is available"
    fi

    echo "$result"
}

# Main function
main() {
    log "INFO" "Starting Cloudflare IP ranges update..."

    # Create log directory if it doesn't exist
    mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null || true

    # Download IPv4 ranges
    log "INFO" "Downloading IPv4 ranges from $CLOUDFLARE_IPV4_URL..."
    IPV4_RANGES=$(download_ip_ranges "$CLOUDFLARE_IPV4_URL") || error_exit "Failed to download IPv4 ranges"

    if [[ -z "$IPV4_RANGES" ]]; then
        error_exit "IPv4 ranges response is empty"
    fi

    # Download IPv6 ranges
    log "INFO" "Downloading IPv6 ranges from $CLOUDFLARE_IPV6_URL..."
    IPV6_RANGES=$(download_ip_ranges "$CLOUDFLARE_IPV6_URL") || error_exit "Failed to download IPv6 ranges"

    if [[ -z "$IPV6_RANGES" ]]; then
        error_exit "IPv6 ranges response is empty"
    fi

    # Create backup of existing config
    if [[ -f "$CONFIG_FILE" ]]; then
        log "INFO" "Creating backup of existing configuration..."
        cp "$CONFIG_FILE" "$BACKUP_FILE"
    fi

    # Generate new configuration
    log "INFO" "Generating new cloudflare-ips.conf..."
    TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

    cat > "$CONFIG_FILE" << EOF
# Cloudflare IP Ranges Configuration
# Auto-generated by update-cloudflare-ips.sh
# Last update: $TIMESTAMP
#
# This file is included by nginx.conf for real_ip module
# to extract the real client IP from behind Cloudflare CDN.
#
# Source: https://www.cloudflare.com/ips-v4 and https://www.cloudflare.com/ips-v6

# Cloudflare IPv4 ranges
EOF

    # Add IPv4 ranges
    while IFS= read -r ip; do
        if [[ -n "$ip" ]]; then
            echo "set_real_ip_from $ip;" >> "$CONFIG_FILE"
        fi
    done <<< "$IPV4_RANGES"

    echo "" >> "$CONFIG_FILE"
    echo "# Cloudflare IPv6 ranges" >> "$CONFIG_FILE"

    # Add IPv6 ranges
    while IFS= read -r ip; do
        if [[ -n "$ip" ]]; then
            echo "set_real_ip_from $ip;" >> "$CONFIG_FILE"
        fi
    done <<< "$IPV6_RANGES"

    log "INFO" "Configuration file generated successfully"

    # Count IP ranges
    IPV4_COUNT=$(echo "$IPV4_RANGES" | wc -l | tr -d ' ')
    IPV6_COUNT=$(echo "$IPV6_RANGES" | wc -l | tr -d ' ')
    log "INFO" "Added $IPV4_COUNT IPv4 ranges and $IPV6_COUNT IPv6 ranges"

    # Test nginx configuration
    log "INFO" "Testing nginx configuration..."

    # Check if running inside Docker or need to use docker-compose
    if command -v nginx &> /dev/null && [[ -f /etc/nginx/nginx.conf ]]; then
        # Running directly on host with nginx installed
        if nginx -t 2>&1; then
            log "INFO" "Nginx configuration test passed"

            log "INFO" "Reloading nginx..."
            if nginx -s reload 2>&1; then
                log "INFO" "Nginx reloaded successfully"
            else
                log "ERROR" "Failed to reload nginx"
                rollback
                exit 1
            fi
        else
            log "ERROR" "Nginx configuration test failed"
            rollback
            exit 1
        fi
    elif command -v docker-compose &> /dev/null || command -v docker &> /dev/null; then
        # Using docker-compose
        cd "$PROJECT_DIR"

        # Try docker compose (newer) first, then docker-compose (legacy)
        if command -v docker &> /dev/null && docker compose version &> /dev/null; then
            COMPOSE_CMD="docker compose"
        else
            COMPOSE_CMD="docker-compose"
        fi

        if $COMPOSE_CMD exec -T nginx nginx -t 2>&1; then
            log "INFO" "Nginx configuration test passed"

            log "INFO" "Reloading nginx..."
            if $COMPOSE_CMD exec -T nginx nginx -s reload 2>&1; then
                log "INFO" "Nginx reloaded successfully"
            else
                log "ERROR" "Failed to reload nginx"
                rollback
                exit 1
            fi
        else
            log "ERROR" "Nginx configuration test failed"
            rollback
            exit 1
        fi
    else
        log "WARN" "Cannot test nginx configuration - nginx and docker-compose not found"
        log "WARN" "Please manually test and reload nginx"
    fi

    # Cleanup old backup (keep only the latest)
    if [[ -f "$BACKUP_FILE" ]]; then
        log "INFO" "Keeping backup file: $BACKUP_FILE"
    fi

    log "INFO" "Cloudflare IP ranges update completed successfully"
}

# Run main function
main "$@"
